name: Pipeline_Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: install dependencies
      run: go test
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up go.js 
        uses: actions/setup-go@v5
        
      
      - name: Install dependencies
        run: go install
      
      - name: Run tests
        run: go tests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Fly deploy
        uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to server
        run: flyctl deploy --remote-only
        env:
            PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}