name: Pipeline_Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set up Fly.js
      uses: actions/setup-fly@v4
      with:
        nod-version: '14'

    - name: install dependencies
      run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Fly deploy
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to server
      - run: flyctl deploy --remote-only
        env:
            PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}
